# Generated by Django 4.2 on 2026-01-05 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        help_text="Photo de profil (max 2MB)",
                        null=True,
                        upload_to="avatars/%Y/%m/",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, help_text="Courte biographie", max_length=500
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="Numéro de téléphone", max_length=20
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, help_text="Localisation", max_length=100
                    ),
                ),
                (
                    "organization",
                    models.CharField(
                        blank=True, help_text="Organisation", max_length=100
                    ),
                ),
                (
                    "job_title",
                    models.CharField(
                        blank=True, help_text="Titre du poste", max_length=100
                    ),
                ),
                (
                    "email_notifications",
                    models.BooleanField(
                        default=True, help_text="Recevoir des notifications par email"
                    ),
                ),
                (
                    "critical_alerts_only",
                    models.BooleanField(
                        default=False,
                        help_text="Recevoir uniquement les alertes critiques",
                    ),
                ),
                (
                    "daily_digest",
                    models.BooleanField(
                        default=False, help_text="Recevoir un résumé quotidien"
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[("dark", "Dark"), ("light", "Light")],
                        default="dark",
                        help_text="Thème de l'interface",
                        max_length=10,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("fr", "Français"), ("en", "English")],
                        default="fr",
                        help_text="Langue de l'interface",
                        max_length=5,
                    ),
                ),
                (
                    "two_factor_enabled",
                    models.BooleanField(
                        default=False, help_text="Authentification à deux facteurs"
                    ),
                ),
                (
                    "login_notifications",
                    models.BooleanField(
                        default=True, help_text="Notifications de connexion"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Profil Utilisateur",
                "verbose_name_plural": "Profils Utilisateurs",
            },
        ),
    ]
