# Generated by Django 5.2.9 on 2025-12-10 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Playbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du playbook')),
                ('description', models.TextField(verbose_name='Description')),
                ('trigger', models.CharField(choices=[('suspicious_ip', 'IP Suspecte'), ('auth_failure', "Échecs d'authentification (5+)"), ('port_scan', 'Scan de ports')], max_length=50, verbose_name='Déclencheur')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('execution_count', models.IntegerField(default=0, verbose_name="Nombre d'exécutions")),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playbooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Playbook',
                'verbose_name_plural': 'Playbooks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('block_ip', 'Bloquer IP'), ('send_email', 'Envoyer notification email'), ('enrich_threat', 'Enrichir avec Threat Intelligence'), ('create_ticket', 'Créer ticket incident')], max_length=50, verbose_name="Type d'action")),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'exécution")),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name="Paramètres de l'action")),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('playbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='playbooks.playbook')),
            ],
            options={
                'verbose_name': 'Action',
                'verbose_name_plural': 'Actions',
                'ordering': ['playbook', 'order'],
            },
        ),
        migrations.CreateModel(
            name='PlaybookExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('running', 'En cours'), ('success', 'Succès'), ('failed', 'Échec'), ('partial', 'Partiel')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('logs', models.JSONField(default=list, verbose_name="Logs d'exécution")),
                ('actions_executed', models.IntegerField(default=0)),
                ('actions_failed', models.IntegerField(default=0)),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playbook_executions', to='incidents.incident')),
                ('playbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='playbooks.playbook')),
            ],
            options={
                'verbose_name': 'Exécution de playbook',
                'verbose_name_plural': 'Exécutions de playbooks',
                'ordering': ['-started_at'],
            },
        ),
    ]
