# Generated by Django 5.2.9 on 2025-12-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.CharField(choices=[('block_ip', 'Bloquer IP'), ('isolate_host', 'Isoler Machine Compromise'), ('scan_antivirus', 'Lancer Scan Antivirus'), ('collect_logs', 'Collecter Logs Forensiques'), ('reset_password', 'Réinitialiser Mot de Passe'), ('quarantine_file', 'Mettre Fichier en Quarantaine'), ('send_email', 'Envoyer Notification Email'), ('enrich_threat', 'Enrichir avec Threat Intelligence'), ('create_ticket', 'Créer Ticket Incident')], max_length=50, verbose_name="Type d'action"),
        ),
        migrations.AlterField(
            model_name='playbook',
            name='trigger',
            field=models.CharField(choices=[('ssh_bruteforce', 'SSH Bruteforce Attack'), ('port_scan', 'Port Scanning'), ('web_attack', 'Web Application Attack'), ('sql_injection', 'SQL Injection'), ('xss', 'Cross-Site Scripting (XSS)'), ('lfi', 'Local File Inclusion (LFI)'), ('command_injection', 'Command Injection'), ('ddos_attack', 'DDoS Attack'), ('malware_c2', 'Malware C2 Communication'), ('suspicious_ip', 'Suspicious IP Activity'), ('auth_failure', 'Authentication Failure')], max_length=50, verbose_name='Déclencheur'),
        ),
    ]
