# Generated by Django 4.2 on 2026-01-05 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0002_alter_incident_incident_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("playbooks", "0002_alter_action_action_type_alter_playbook_trigger"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="action",
            options={},
        ),
        migrations.AlterModelOptions(
            name="playbook",
            options={},
        ),
        migrations.AlterModelOptions(
            name="playbookexecution",
            options={},
        ),
        migrations.RemoveField(
            model_name="playbook",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="action",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("block_ip", "Block IP"),
                    ("send_email", "Send Email"),
                    ("enrich_threat", "Threat Intel"),
                    ("create_ticket", "Create Ticket"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="action",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="action",
            name="parameters",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="playbook",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="playbook",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="playbook",
            name="execution_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="playbook",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="playbook",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="playbook",
            name="trigger",
            field=models.CharField(
                choices=[
                    ("ssh_bruteforce", "SSH Bruteforce"),
                    ("port_scan", "Port Scan"),
                    ("web_attack", "Web Attack"),
                    ("ddos_attack", "DDoS"),
                    ("suspicious_ip", "Suspicious IP"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="playbookexecution",
            name="incident",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="playbook_executions",
                to="incidents.incident",
            ),
        ),
        migrations.AlterField(
            model_name="playbookexecution",
            name="logs",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="playbookexecution",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                    ("partial", "Partial"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
