# Generated by Django 5.2.9 on 2025-12-10 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('incident_type', models.CharField(choices=[('suspicious_ip', 'IP Suspecte'), ('auth_failure', "Échecs d'authentification"), ('port_scan', 'Scan de ports')], max_length=50, verbose_name="Type d'incident")),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20, verbose_name='Criticité')),
                ('status', models.CharField(choices=[('new', 'Nouveau'), ('in_progress', 'En cours'), ('resolved', 'Résolu'), ('false_positive', 'Faux positif')], default='new', max_length=20, verbose_name='Statut')),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Source')),
                ('target_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Cible')),
                ('port', models.IntegerField(blank=True, null=True, verbose_name='Port')),
                ('raw_log', models.JSONField(default=dict, verbose_name='Log brut')),
                ('threat_intel_data', models.JSONField(blank=True, default=dict, verbose_name='Données Threat Intelligence')),
                ('is_enriched', models.BooleanField(default=False, verbose_name='Enrichi')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('auto_playbook_triggered', models.BooleanField(default=False, verbose_name='Playbook déclenché')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incidents',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True, verbose_name='Adresse IP')),
                ('reason', models.TextField(verbose_name='Raison du blocage')),
                ('blocked_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Blocage actif')),
                ('unblocked_at', models.DateTimeField(blank=True, null=True)),
                ('blocked_by_incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_ips', to='incidents.incident')),
            ],
            options={
                'verbose_name': 'IP Bloquée',
                'verbose_name_plural': 'IPs Bloquées',
                'ordering': ['-blocked_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='incidents.incident')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['-detected_at'], name='incidents_i_detecte_7ea0db_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['status'], name='incidents_i_status_9a4f12_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['severity'], name='incidents_i_severit_10e3a5_idx'),
        ),
    ]
