# Generated by Django 5.2.9 on 2025-12-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='incident_type',
            field=models.CharField(choices=[('ssh_bruteforce', 'SSH Bruteforce Attack'), ('auth_failure', 'Authentication Failure'), ('port_scan', 'Port Scanning'), ('suspicious_ip', 'Suspicious IP Activity'), ('sql_injection', 'SQL Injection'), ('xss', 'Cross-Site Scripting'), ('web_attack', 'Web Application Attack'), ('ddos_attack', 'DDoS Attack'), ('malware_detected', 'Malware Detected'), ('command_injection', 'Command Injection'), ('lfi', 'Local File Inclusion')], max_length=50, verbose_name="Type d'incident"),
        ),
    ]
